default: &default
  sync_users:
    class: UserSyncJob
    queue: default
    schedule: every 5 minutes
  sync_series:
    class: SeriesSyncJob
    queue: default
    schedule: every 5 minutes

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
