name: Docker Build Check

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'bin/docker-entrypoint'
      - 'Gemfile*'
      - 'config/**'
      - 'app/**'
      - 'lib/**'
      - '.github/workflows/docker-build-check.yml'
      - '.github/workflows/docker-publish.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          ./bin/docker-build \
            --load \
            --tag tvdb-calendar:test \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .

      - name: Test Docker image
        run: |
          # Generate a test secret key
          TEST_SECRET=$(openssl rand -hex 64)
          
          # Test that the image can start with environment variables
          docker run --rm \
            -e SECRET_KEY_BASE=$TEST_SECRET \
            -e TVDB_API_KEY=test_key_for_ci \
            tvdb-calendar:test \
            ./bin/rails runner "puts 'Docker build test: SUCCESS'"

      - name: Generate build summary
        run: |
          echo "## Docker Build Check ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The Docker image builds successfully and can start with the required environment variables." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Required Environment Variables Tested:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`SECRET_KEY_BASE\` ✅" >> $GITHUB_STEP_SUMMARY
          echo "- \`TVDB_API_KEY\` ✅" >> $GITHUB_STEP_SUMMARY